<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE language [
    <!ELEMENT language ANY>
    <!ELEMENT locale ANY>
    <!ELEMENT text (source,output)>
    <!ELEMENT source ANY>
    <!ELEMENT output ANY>
    <!ATTLIST language
        src       CDATA    #REQUIRED
        output    CDATA    #REQUIRED
        name      CDATA    #REQUIRED
        native    CDATA    #REQUIRED
    >
    <!ATTLIST locale
        region    CDATA    #REQUIRED
        name      CDATA    #REQUIRED
        native    CDATA    #REQUIRED
    >
]>
<language src="en" output="ja" name="Japanese" native="日本">
    <locale region="JA" name="Japan" native="日本">
        <text>
            <source>This field is required.</source>
            <output>このフィールドは必須です。</output>
        </text>
        <text>
            <source>January</source>
            <output>月</output>
        </text>
        <text>
            <source>February</source>
            <output>月</output>
        </text>
        <text>
            <source>March</source>
            <output>月</output>
        </text>
        <text>
            <source>April</source>
            <output>月</output>
        </text>
        <text>
            <source>May</source>
            <output>5月</output>
        </text>
        <text>
            <source>June</source>
            <output>月</output>
        </text>
        <text>
            <source>July</source>
            <output>月</output>
        </text>
        <text>
            <source>August</source>
            <output>月</output>
        </text>
        <text>
            <source>September</source>
            <output>月</output>
        </text>
        <text>
            <source>October</source>
            <output>月</output>
        </text>
        <text>
            <source>November</source>
            <output>11月</output>
        </text>
        <text>
            <source>December</source>
            <output>月</output>
        </text>
        <text>
            <source>Sunday</source>
            <output>日曜日</output>
        </text>
        <text>
            <source>Monday</source>
            <output>月</output>
        </text>
        <text>
            <source>Tuesday</source>
            <output>火曜日</output>
        </text>
        <text>
            <source>Wednesday</source>
            <output>水曜日</output>
        </text>
        <text>
            <source>Thursday</source>
            <output>木曜日</output>
        </text>
        <text>
            <source>Friday</source>
            <output>金曜日</output>
        </text>
        <text>
            <source>Saturday</source>
            <output>土曜日</output>
        </text>
        <text>
            <source>The value length must be between or equal to %1 and %2.</source>
            <output>値の長さは間または%1と%2以下である必要があります。</output>
        </text>
        <text>
            <source>The value length must not be between or equal to %1 and %2.</source>
            <output>値の長さは間または%1と%2に等しくてはならない。</output>
        </text>
        <text>
            <source>The value must be a valid IPv6 address.</source>
            <output>値は有効なIPv6アドレスでなければなりません。</output>
        </text>
        <text>
            <source>The value must not be a valid IPv6 address.</source>
            <output>値は有効なIPv6アドレスである必要があります。</output>
        </text>
        <text>
            <source>The value must be a valid credit card number.</source>
            <output>値は有効なクレジットカードの番号でなければなりません。</output>
        </text>
        <text>
            <source>The value must not be a valid credit card number.</source>
            <output>値は有効なクレジットカードの番号であってはなりません。</output>
        </text>
        <text>
            <source>The value must be included.</source>
            <output>値が含まれている必要があります。</output>
        </text>
        <text>
            <source>The value must not be included.</source>
            <output>値を含めることはできません。</output>
        </text>
        <text>
            <source>The value must be between or equal to %1 and %2.</source>
            <output>値の間または%1と%2以下である必要があります。</output>
        </text>
        <text>
            <source>The value must not be between or equal to %1 and %2.</source>
            <output>値の間または%1と%2に等しくてはならない。</output>
        </text>
        <text>
            <source>The value must be part of the subnet %1.</source>
            <output>値はサブネット%1の一部である必要があります。</output>
        </text>
        <text>
            <source>The value must not be part of the subnet %1.</source>
            <output>値はサブネット%1の一部であってはなりません。</output>
        </text>
        <text>
            <source>The value must be greater than or equal to %1.</source>
            <output>値がより大きいまたは%1でなければならない。</output>
        </text>
        <text>
            <source>The value must not be greater than or equal to %1.</source>
            <output>値がより大きいまたは%1に等しくてはならない。</output>
        </text>
        <text>
            <source>The value length must be greater than %1.</source>
            <output>値の長さは%1よりも大きくなければなりません。</output>
        </text>
        <text>
            <source>The value length must not be greater than %1.</source>
            <output>値の長さは%1を超えてはなりません。</output>
        </text>
        <text>
            <source>The value must only contain alphanumeric characters.</source>
            <output>値は英数字のみを含める必要があります。</output>
        </text>
        <text>
            <source>The value must contain non-alphanumeric characters.</source>
            <output>値は、英数字以外の文字が含まれている必要があります。</output>
        </text>
        <text>
            <source>The value length must be equal to %1.</source>
            <output>値の長さは%1でなければならない。</output>
        </text>
        <text>
            <source>The value length must not be equal to %1.</source>
            <output>値の長さは%1に等しくてはならない。</output>
        </text>
        <text>
            <source>The value length must be greater than or equal to %1.</source>
            <output>値の長さより大きいか%1でなければならない。</output>
        </text>
        <text>
            <source>The value length must not be greater than or equal to %1.</source>
            <output>値の長さより大きいか%1に等しくてはならない。</output>
        </text>
        <text>
            <source>The value must be less than or equal to %1.</source>
            <output>値がより小さいか%1でなければならない。</output>
        </text>
        <text>
            <source>The value must not be less than or equal to %1.</source>
            <output>値がより小さいまたは%1に等しくてはならない。</output>
        </text>
        <text>
            <source>The value must be between %1 and %2.</source>
            <output>値は%1と%2の間でなければなりません。</output>
        </text>
        <text>
            <source>The value must not be between %1 and %2.</source>
            <output>値は%1と%2の間であってはなりません。</output>
        </text>
        <text>
            <source>The value must be greater than %1.</source>
            <output>値は%1より大きくなければなりません。</output>
        </text>
        <text>
            <source>The value must not be greater than %1.</source>
            <output>値は%1を超えてはなりません。</output>
        </text>
        <text>
            <source>The value must be a valid IPv4 address.</source>
            <output>値は有効なIPv4アドレスでなければなりません。</output>
        </text>
        <text>
            <source>The value must not be a valid IPv4 address.</source>
            <output>値は有効なIPv4アドレスでなければなりません。</output>
        </text>
        <text>
            <source>The value must be a valid email format.</source>
            <output>値は有効な電子メール形式である必要があります。</output>
        </text>
        <text>
            <source>The value must not be a valid email format.</source>
            <output>値は有効な電子メール形式である必要があります。</output>
        </text>
        <text>
            <source>The value must be a valid IPv4 subnet.</source>
            <output>値は有効なIPv4サブネットでなければなりません。</output>
        </text>
        <text>
            <source>The value must not be a valid IPv4 subnet.</source>
            <output>値は有効なIPv4サブネットであってはならない。</output>
        </text>
        <text>
            <source>The value format is not correct.</source>
            <output>値の形式が正しくありません。</output>
        </text>
        <text>
            <source>The value must be equal to %1.</source>
            <output>値は%1でなければならない。</output>
        </text>
        <text>
            <source>The value must not be equal to %1.</source>
            <output>値は%1に等しくてはならない。</output>
        </text>
        <text>
            <source>The value must be less than %1.</source>
            <output>値は%1未満にする必要があります。</output>
        </text>
        <text>
            <source>The value must not be less than %1.</source>
            <output>値は%1以上でなければなりません。</output>
        </text>
        <text>
            <source>The value length must be between %1 and %2.</source>
            <output>値の長さは%1と%2の間でなければなりません。</output>
        </text>
        <text>
            <source>The value length must not be between %1 and %2.</source>
            <output>値の長さは%1と%2の間であってはなりません。</output>
        </text>
        <text>
            <source>The value must be numeric.</source>
            <output>値は数値でなければなりません。</output>
        </text>
        <text>
            <source>The value must not be numeric.</source>
            <output>値が数字であってはいけません。</output>
        </text>
        <text>
            <source>The value must not be empty.</source>
            <output>値が空であってはなりません。</output>
        </text>
        <text>
            <source>The value must be empty.</source>
            <output>値は空である必要があります。</output>
        </text>
        <text>
            <source>The value length must be less than %1.</source>
            <output>値の長さは%1未満にする必要があります。</output>
        </text>
        <text>
            <source>The value length must not be less than %1.</source>
            <output>値の長さは%1以上でなければなりません。</output>
        </text>
        <text>
            <source>The value must only contain characters in the alphabet.</source>
            <output>値はアルファベットの文字のみが含まれている必要があります。</output>
        </text>
        <text>
            <source>The value must only contain characters not in the alphabet.</source>
            <output>値はアルファベットの文字を唯一ではないが含まれている必要があります。</output>
        </text>
        <text>
            <source>The value must be excluded.</source>
            <output>値を除外する必要があります。</output>
        </text>
        <text>
            <source>The value must not be excluded.</source>
            <output>値は除外してはいけません。</output>
        </text>
        <text>
            <source>The value length must be less than or equal to %1.</source>
            <output>値の長さがより小さいか%1でなければならない。</output>
        </text>
        <text>
            <source>The value length must not be less than or equal to %1.</source>
            <output>値の長さがより小さいまたは%1に等しくてはならない。</output>
        </text>
        <text>
            <source>The value must not be equal to %1.</source>
            <output>値は%1に等しくてはならない。</output>
        </text>
        <text>
            <source>The value must be equal to %1.</source>
            <output>値は%1でなければならない。</output>
        </text>
        <text>
            <source>Creating controller class files...</source>
            <output>コントローラクラスファイルを作成しています...</output>
        </text>
        <text>
            <source>Creating base folder and file structure...</source>
            <output>ベースフォルダとファイル構造を作成しています...</output>
        </text>
        <text>
            <source>Creating database table class files...</source>
            <output>データベースのテーブルのクラスファイルを作成しています...</output>
        </text>
        <text>
            <source>Creating form class files...</source>
            <output>フォームのクラスファイルを作成しています...</output>
        </text>
        <text>
            <source>Creating model class files...</source>
            <output>モデルクラスのファイルを作成しています...</output>
        </text>
        <text>
            <source>You will have to install your web server rewrite configuration manually.</source>
            <output>手動でWebサーバーの書き換え設定をインストールする必要があります。</output>
        </text>
        <text>
            <source>Install index controller and web configuration files?</source>
            <output>インデックスのコントローラおよびWeb構成ファイルをインストールするのか？</output>
        </text>
        <text>
            <source>The user is valid.</source>
            <output>ユーザーが有効です。</output>
        </text>
        <text>
            <source>The user was not found.</source>
            <output>ユーザーが見つかりませんでした。</output>
        </text>
        <text>
            <source>The user is blocked.</source>
            <output>ユーザーはブロッ​​クされます。</output>
        </text>
        <text>
            <source>The password was incorrect.</source>
            <output>パスワードが正しくありません。</output>
        </text>
        <text>
            <source>The allowed login attempts (%1) have been exceeded.</source>
            <output>許可されたログイン試行（%1）を超えている。</output>
        </text>
        <text>
            <source>That IP address is blocked.</source>
            <output>そのIPアドレスがブロックされます。</output>
        </text>
        <text>
            <source>That IP address is not allowed.</source>
            <output>そのIPアドレスは許可されていません。</output>
        </text>
        <text>
            <source>The session has expired.</source>
            <output>セッションの有効期限が切れました。</output>
        </text>
        <text>
            <source>Aborted.</source>
            <output>中止された。</output>
        </text>
        <text>
            <source>Project folder exists. This may overwrite any project files you may already have under that project folder.</source>
            <output>プロジェクトのフォルダが存在する。これは、すでにそのプロジェクトフォルダの下に持っている可能性のあるすべてのプロジェクトファイルが上書きされる可能性があります。</output>
        </text>
        <text>
            <source>Database credentials and schema detected.</source>
            <output>データベースの資格情報とスキーマが検出された。</output>
        </text>
        <text>
            <source>Test and install the database(s)?</source>
            <output>データベース（複数可）をテストし、インストールする？</output>
        </text>
        <text>
            <source>Testing the database(s)...</source>
            <output>データベース（複数可）をテストする...</output>
        </text>
        <text>
            <source>Testing</source>
            <output>テスト</output>
        </text>
        <text>
            <source>The database type and database name must be set for the database</source>
            <output>データベースのタイプおよびデータベース名がデータベースに設定する必要があります。</output>
        </text>
        <text>
            <source>Database</source>
            <output>データベース</output>
        </text>
        <text>
            <source>Installing database</source>
            <output>データベースのインストール</output>
        </text>
        <text>
            <source>Project install complete.</source>
            <output>完全なインストール投影。</output>
        </text>
        <text>
            <source>The Pop autoloader class file was not found.</source>
            <output>ポップオートローダのクラスファイルが見つかりませんでした。</output>
        </text>
        <text>
            <source>Pop PHP Framework found.</source>
            <output>ポップPHPフレームワークのデータが見つかりました。</output>
        </text>
        <text>
            <source>Project reconfigured.</source>
            <output>プロジェクトを再構成。</output>
        </text>
        <text>
            <source>This process will create and install the base foundation of your project under the folder specified in the install file. Minimally, the install file should return a Pop\Config object containing your project install settings, such as project name, folders, forms, controllers, views and any database credentials.</source>
            <output>このプロセスは、インストールファイルで指定されたフォルダの下にプロジェクトのベース基盤を作成し、インストールします。最低限、インストールファイルには、プロジェクト名、フォルダ、フォーム、コントローラー、ビュー、および任意のデータベースの資格情報として、プロジェクトのインストール設定を含むポップ\ \ Configオブジェクトを、返さなければなりません。</output>
        </text>
        <text>
            <source>Besides creating the base folders and files for you, one of the main benefits is ability to test and install the database and the corresponding configuration and class files. You can take advantage of this by having the database SQL files in the same folder as your install file, like so:</source>
            <output>あなたのためのベースフォルダとファイルを作成する以外に、主な利点の一つは、データベースと対応する構成とクラスファイルをテストしてインストールする機能です。次のように、あなたのインストールファイルと同じフォルダにデータベースのSQLファイルを持っていることによってこれを活用することができます。</output>
        </text>
        <text>
            <source>Check the current configuration for required dependencies</source>
            <output>必要な依存関係のための現在の設定を確認してください</output>
        </text>
        <text>
            <source>Display this help</source>
            <output>このヘルプを表示する</output>
        </text>
        <text>
            <source>Install a project based on the install file specified</source>
            <output>指定したインストールファイルに基づいてプロジェクトをインストールします。</output>
        </text>
        <text>
            <source>Set the default language for the project</source>
            <output>プロジェクトで使用するデフォルト言語を設定する</output>
        </text>
        <text>
            <source>Create a class map file from the source folder and save to the output file</source>
            <output>ソースフォルダからクラスマップファイルを作成し、出力ファイルに保存</output>
        </text>
        <text>
            <source>Reconfigure the project based on the new location of the project</source>
            <output>プロジェクトの新しい位置に基づいて再構成するプロジェクト</output>
        </text>
        <text>
            <source>Show project install instructions</source>
            <output>プロジェクトのインストール手順を表示</output>
        </text>
        <text>
            <source>Display version of Pop PHP Framework and latest available</source>
            <output>ポップPHPフレームワークと利用可能な最新のバージョンを表示</output>
        </text>
        <text>
            <source>Run './pop -h' for help.</source>
            <output>助けのために"。/ポップアップh'を実行する。</output>
        </text>
        <text>
            <source>Run '.\pop -h' for help.</source>
            <output>助けのために"。\ポップアップh'を実行します。</output>
        </text>
        <text>
            <source>Continue?</source>
            <output>続行しますか？</output>
        </text>
        <text>
            <source>Enter the folder where the 'bootstrap.php' is located in relation to the current folder:</source>
            <output>"bootstrap.phpのは"現在のフォルダとの関係で配置されているフォルダを入力します。</output>
        </text>
        <text>
            <source>Bootstrap file not found. Try again.</source>
            <output>ブートストラップファイルが見つかりません。もう一度やり直してください。</output>
        </text>
        <text>
            <source>Enter the folder where the 'vendor' folder is contained in relation to the current folder:</source>
            <output>"ベンダー"フォルダがカレントフォルダとの関係で含まれているフォルダを入力します。</output>
        </text>
        <text>
            <source>Pop PHP Framework not found. Try again.</source>
            <output>ポップPHPフレームワークが見つかりません。もう一度やり直してください。</output>
        </text>
        <text>
            <source>Enter the numeric code for the default language: </source>
            <output>デフォルト言語の数字コードを入力してください： </output>
        </text>
        <text>
            <source>Unknown error.</source>
            <output>不明なエラー。</output>
        </text>
        <text>
            <source>You must pass a source folder and a output file to generate a class map file.</source>
            <output>あなたは、クラスマップファイルを生成するソースフォルダと出力ファイルを渡す必要があります。</output>
        </text>
        <text>
            <source>The source folder passed does not exist.</source>
            <output>渡されたソースフォルダが存在しません。</output>
        </text>
        <text>
            <source>The output file passed must be a PHP file.</source>
            <output>渡された出力ファイルはPHPファイルである必要があります。</output>
        </text>
        <text>
            <source>You must pass an install file to install the project.</source>
            <output>あなたがプロジェクトをインストールするためには、インストールファイルを渡す必要があります。</output>
        </text>
        <text>
            <source>Unknown option:</source>
            <output>不明なオプション：</output>
        </text>
        <text>
            <source>You must pass at least one argument.</source>
            <output>あなたは、少なくとも1つの引数を渡す必要があります。</output>
        </text>
        <text>
            <source>That folder does not exist.</source>
            <output>そのフォルダが存在しません。</output>
        </text>
        <text>
            <source>The folder argument is not a folder</source>
            <output>フォルダの引数はフォルダではない</output>
        </text>
        <text>
            <source>A few seconds ago</source>
            <output>数秒前</output>
        </text>
        <text>
            <source>1 minute ago</source>
            <output>1分前</output>
        </text>
        <text>
            <source>1 hour ago</source>
            <output>1時間前</output>
        </text>
        <text>
            <source>1 day ago</source>
            <output>1日前</output>
        </text>
        <text>
            <source>1 month ago</source>
            <output>1ヶ月前</output>
        </text>
        <text>
            <source>%1 minutes ago</source>
            <output>%1分前</output>
        </text>
        <text>
            <source>%1 hours ago</source>
            <output>%1時間前</output>
        </text>
        <text>
            <source>%1 days ago</source>
            <output>%1日前</output>
        </text>
        <text>
            <source>%1 months ago</source>
            <output>%1ヶ月前</output>
        </text>
        <text>
            <source>%1 years ago</source>
            <output>%1年前</output>
        </text>
        <text>
            <source>The answer is incorrect.</source>
            <output>答えは間違っています。</output>
        </text>
        <text>
            <source>The security token does not match.</source>
            <output>セキュリティトークンが一致していません。</output>
        </text>
    </locale>
</language>