<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE options [
    <!ELEMENT options ANY>
    <!ELEMENT set ANY>
    <!ELEMENT opt ANY>
    <!ATTLIST set
        name    CDATA    #REQUIRED
        desc    CDATA    #REQUIRED
    >
    <!ATTLIST opt
        value   CDATA    #REQUIRED
    >
]>
<options>
    <set name="MONTHS_LONG" desc="Months, long name value">
        <opt value="--">------</opt>
        <opt value="01">January</opt>
        <opt value="02">February</opt>
        <opt value="03">March</opt>
        <opt value="04">April</opt>
        <opt value="05">May</opt>
        <opt value="06">June</opt>
        <opt value="07">July</opt>
        <opt value="08">August</opt>
        <opt value="09">September</opt>
        <opt value="10">October</opt>
        <opt value="11">November</opt>
        <opt value="12">December</opt>
    </set>
    <set name="DAYS_OF_WEEK" desc="Days of the week">
        <opt value="--">--</opt>
        <opt value="Sunday">Sunday</opt>
        <opt value="Monday">Monday</opt>
        <opt value="Tuesday">Tuesday</opt>
        <opt value="Wednesday">Wednesday</opt>
        <opt value="Thursday">Thursday</opt>
        <opt value="Friday">Friday</opt>
        <opt value="Saturday">Saturday</opt>
    </set>
    <set name="US_STATES_SHORT" desc="US states, short name values">
        <opt value="--">--</opt>
        <opt value="AK">AK</opt>
        <opt value="AL">AL</opt>
        <opt value="AR">AR</opt>
        <opt value="AZ">AZ</opt>
        <opt value="CA">CA</opt>
        <opt value="CO">CO</opt>
        <opt value="CT">CT</opt>
        <opt value="DC">DC</opt>
        <opt value="DE">DE</opt>
        <opt value="FL">FL</opt>
        <opt value="GA">GA</opt>
        <opt value="HI">HI</opt>
        <opt value="IA">IA</opt>
        <opt value="ID">ID</opt>
        <opt value="IL">IL</opt>
        <opt value="IN">IN</opt>
        <opt value="KS">KS</opt>
        <opt value="KY">KY</opt>
        <opt value="LA">LA</opt>
        <opt value="MA">MA</opt>
        <opt value="MD">MD</opt>
        <opt value="ME">ME</opt>
        <opt value="MI">MI</opt>
        <opt value="MN">MN</opt>
        <opt value="MO">MO</opt>
        <opt value="MS">MS</opt>
        <opt value="MT">MT</opt>
        <opt value="NC">NC</opt>
        <opt value="ND">ND</opt>
        <opt value="NE">NE</opt>
        <opt value="NH">NH</opt>
        <opt value="NJ">NJ</opt>
        <opt value="NM">NM</opt>
        <opt value="NV">NV</opt>
        <opt value="NY">NY</opt>
        <opt value="OH">OH</opt>
        <opt value="OK">OK</opt>
        <opt value="OR">OR</opt>
        <opt value="PA">PA</opt>
        <opt value="RI">RI</opt>
        <opt value="SC">SC</opt>
        <opt value="SD">SD</opt>
        <opt value="TN">TN</opt>
        <opt value="TX">TX</opt>
        <opt value="UT">UT</opt>
        <opt value="VA">VA</opt>
        <opt value="VT">VT</opt>
        <opt value="WA">WA</opt>
        <opt value="WI">WI</opt>
        <opt value="WV">WV</opt>
        <opt value="WY">WY</opt>
    </set>
    <set name="US_STATES_LONG" desc="US states, long name values">
        <opt value="--">------</opt>
        <opt value="AL">Alabama</opt>
        <opt value="AK">Alaska</opt>
        <opt value="AZ">Arizona</opt>
        <opt value="AR">Arkansas</opt>
        <opt value="CA">California</opt>
        <opt value="CO">Colorado</opt>
        <opt value="CT">Connecticut</opt>
        <opt value="DC">District of Columbia</opt>
        <opt value="DE">Delaware</opt>
        <opt value="FL">Florida</opt>
        <opt value="GA">Georgia</opt>
        <opt value="HI">Hawaii</opt>
        <opt value="ID">Idaho</opt>
        <opt value="IL">Illinois</opt>
        <opt value="IN">Indiana</opt>
        <opt value="IA">Iowa</opt>
        <opt value="KS">Kansas</opt>
        <opt value="KY">Kentucky</opt>
        <opt value="LA">Louisiana</opt>
        <opt value="ME">Maine</opt>
        <opt value="MD">Maryland</opt>
        <opt value="MA">Massachusetts</opt>
        <opt value="MI">Michigan</opt>
        <opt value="MN">Minnesota</opt>
        <opt value="MS">Mississippi</opt>
        <opt value="MO">Missouri</opt>
        <opt value="MT">Montana</opt>
        <opt value="NE">Nebraska</opt>
        <opt value="NV">Nevada</opt>
        <opt value="NH">New Hampshire</opt>
        <opt value="NJ">New Jersey</opt>
        <opt value="NM">New Mexico</opt>
        <opt value="NY">New York</opt>
        <opt value="NC">North Carolina</opt>
        <opt value="ND">North Dakota</opt>
        <opt value="OH">Ohio</opt>
        <opt value="OK">Oklahoma</opt>
        <opt value="OR">Oregon</opt>
        <opt value="PA">Pennsylvania</opt>
        <opt value="RI">Rhode Island</opt>
        <opt value="SC">South Carolina</opt>
        <opt value="SD">South Dakota</opt>
        <opt value="TN">Tennessee</opt>
        <opt value="TX">Texas</opt>
        <opt value="UT">Utah</opt>
        <opt value="VT">Vermont</opt>
        <opt value="VA">Virginia</opt>
        <opt value="WA">Washington</opt>
        <opt value="WV">West Virginia</opt>
        <opt value="WI">Wisconsin</opt>
        <opt value="WY">Wyoming</opt>
    </set>
    <set name="US_TERR_SHORT" desc="US Territories, short name values">
        <opt value="--">--</opt>
        <opt value="AS">AS</opt>
        <opt value="FM">FM</opt>
        <opt value="GU">GU</opt>
        <opt value="MH">MH</opt>
        <opt value="MP">MP</opt>
        <opt value="PW">PW</opt>
        <opt value="PR">PR</opt>
        <opt value="VI">VI</opt>
        <opt value="AE">AE</opt>
        <opt value="AA">AA</opt>
        <opt value="AP">AP</opt>
    </set>
    <set name="US_TERR_LONG" desc="US Territories, long name values">
        <opt value="--">------</opt>
        <opt value="AS">American Samoa</opt>
        <opt value="FM">Federated States of Micronesia</opt>
        <opt value="GU">Guam</opt>
        <opt value="MH">Marshall Islands</opt>
        <opt value="MP">Northern Mariana Islands</opt>
        <opt value="PW">Palau</opt>
        <opt value="PR">Puerto Rico</opt>
        <opt value="VI">Virgin Islands</opt>
        <opt value="AE">Armed Forces</opt>
        <opt value="AA">Armed Forces Americas</opt>
        <opt value="AP">Armed Forces Pacific</opt>
    </set>
    <set name="CA_PROVINCES_SHORT" desc="Canadian Provinces, short name values">
        <opt value="--">--</opt>
        <opt value="AB">AB</opt>
        <opt value="BC">BC</opt>
        <opt value="MB">MB</opt>
        <opt value="NB">NB</opt>
        <opt value="NL">NL</opt>
        <opt value="NT">NT</opt>
        <opt value="NS">NS</opt>
        <opt value="NU">NU</opt>
        <opt value="ON">ON</opt>
        <opt value="PE">PE</opt>
        <opt value="QC">QC</opt>
        <opt value="SK">SK</opt>
        <opt value="YT">YT</opt>
    </set>
    <set name="CA_PROVINCES_LONG" desc="Canadian Provinces, long name values">
        <opt value="--">------</opt>
        <opt value="AB">Alberta</opt>
        <opt value="BC">British Columbia</opt>
        <opt value="MB">Manitoba</opt>
        <opt value="NB">New Brunswick</opt>
        <opt value="NL">Newfoundland and Labrador</opt>
        <opt value="NT">Northwest Territories</opt>
        <opt value="NS">Nova Scotia</opt>
        <opt value="NU">Nunavut</opt>
        <opt value="ON">Ontario</opt>
        <opt value="PE">Prince Edward Island</opt>
        <opt value="QC">Quebec</opt>
        <opt value="SK">Saskatchewan</opt>
        <opt value="YT">Yukon</opt>
    </set>
    <set name="MEX_STATES_SHORT" desc="Mexican States, short name values">
        <opt value="--">--</opt>
        <opt value="AG">AG</opt>
        <opt value="BC">BC</opt>
        <opt value="BS">BS</opt>
        <opt value="CM">CM</opt>
        <opt value="CS">CS</opt>
        <opt value="CH">CH</opt>
        <opt value="CO">CO</opt>
        <opt value="CL">CL</opt>
        <opt value="DF">DF</opt>
        <opt value="DG">DG</opt>
        <opt value="GT">GT</opt>
        <opt value="GR">GR</opt>
        <opt value="HG">HG</opt>
        <opt value="JA">JA</opt>
        <opt value="ME">ME</opt>
        <opt value="MI">MI</opt>
        <opt value="MO">MO</opt>
        <opt value="NA">NA</opt>
        <opt value="NL">NL</opt>
        <opt value="OA">OA</opt>
        <opt value="PB">PB</opt>
        <opt value="QE">QE</opt>
        <opt value="QR">QR</opt>
        <opt value="SL">SL</opt>
        <opt value="SI">SI</opt>
        <opt value="SO">SO</opt>
        <opt value="TB">TB</opt>
        <opt value="TM">TM</opt>
        <opt value="TL">TL</opt>
        <opt value="VE">VE</opt>
        <opt value="YU">YU</opt>
        <opt value="ZA">ZA</opt>
    </set>
    <set name="MEX_STATES_LONG" desc="Mexican states, long name values">
        <opt value="--">------</opt>
        <opt value="AG">Aguascalientes</opt>
        <opt value="BC">Baja California</opt>
        <opt value="BS">Baja California Sur</opt>
        <opt value="CM">Campeche</opt>
        <opt value="CS">Chiapas</opt>
        <opt value="CH">Chihuahua</opt>
        <opt value="CO">Coahuila</opt>
        <opt value="CL">Colima</opt>
        <opt value="DF">Federal District</opt>
        <opt value="DG">Durango</opt>
        <opt value="GT">Guanajuato</opt>
        <opt value="GR">Guerrero</opt>
        <opt value="HG">Hidalgo</opt>
        <opt value="JA">Jalisco</opt>
        <opt value="ME">Mexico State</opt>
        <opt value="MI">Michoac&#225;n</opt>
        <opt value="MO">Morelos</opt>
        <opt value="NA">Nayarit</opt>
        <opt value="NL">Nuevo Le&#243;n</opt>
        <opt value="OA">Oaxaca</opt>
        <opt value="PB">Puebla</opt>
        <opt value="QE">Quer&#233;taro</opt>
        <opt value="QR">Quintana Roo</opt>
        <opt value="SL">San Luis Potos&#237;</opt>
        <opt value="SI">Sinaloa</opt>
        <opt value="SO">Sonora</opt>
        <opt value="TB">Tabasco</opt>
        <opt value="TM">Tamaulipas</opt>
        <opt value="TL">Tlaxcala</opt>
        <opt value="VE">Veracruz</opt>
        <opt value="YU">Yucat&#225;n</opt>
        <opt value="ZA">Zacatecas</opt>
    </set>
    <set name="COUNTRIES" desc="Countries">
        <opt value="--">------</opt>
        <opt value="AF">Afghanistan</opt>
        <opt value="AL">Albania</opt>
        <opt value="DZ">Algeria</opt>
        <opt value="AS">American Samoa</opt>
        <opt value="AD">Andorra</opt>
        <opt value="AO">Angola</opt>
        <opt value="AI">Anguilla</opt>
        <opt value="AQ">Antarctica</opt>
        <opt value="AG">Antigua and Barbuda</opt>
        <opt value="AR">Argentina</opt>
        <opt value="AM">Armenia</opt>
        <opt value="AW">Aruba</opt>
        <opt value="AU">Australia</opt>
        <opt value="AT">Austria</opt>
        <opt value="AZ">Azerbaijan</opt>
        <opt value="BS">Bahamas</opt>
        <opt value="BH">Bahrain</opt>
        <opt value="BD">Bangladesh</opt>
        <opt value="BB">Barbados</opt>
        <opt value="BY">Belarus</opt>
        <opt value="BE">Belgium</opt>
        <opt value="BZ">Belize</opt>
        <opt value="BJ">Benin</opt>
        <opt value="BM">Bermuda</opt>
        <opt value="BT">Bhutan</opt>
        <opt value="BO">Bolivia</opt>
        <opt value="BA">Bosnia and Herzegowina</opt>
        <opt value="BW">Botswana</opt>
        <opt value="BV">Bouvet Island</opt>
        <opt value="BR">Brazil</opt>
        <opt value="IO">British Indian Ocean Territory</opt>
        <opt value="BN">Brunei Darussalam</opt>
        <opt value="BG">Bulgaria</opt>
        <opt value="BF">Burkina Faso</opt>
        <opt value="BI">Burundi</opt>
        <opt value="KH">Cambodia</opt>
        <opt value="CM">Cameroon</opt>
        <opt value="CA">Canada</opt>
        <opt value="CV">Cape Verde</opt>
        <opt value="KY">Cayman Islands</opt>
        <opt value="CF">Central African Republic</opt>
        <opt value="TD">Chad</opt>
        <opt value="CL">Chile</opt>
        <opt value="CN">China</opt>
        <opt value="CX">Christmas Island</opt>
        <opt value="CC">Cocos (Keeling) Islands</opt>
        <opt value="CO">Colombia</opt>
        <opt value="KM">Comoros</opt>
        <opt value="CG">Republic of the Congo</opt>
        <opt value="CD">Democratic Republic of the Congo</opt>
        <opt value="CK">Cook Islands</opt>
        <opt value="CR">Costa Rica</opt>
        <opt value="CI">Cote d&#39;Ivoire</opt>
        <opt value="HR">Croatia (Hrvatska)</opt>
        <opt value="CU">Cuba</opt>
        <opt value="CY">Cyprus</opt>
        <opt value="CZ">Czech Republic</opt>
        <opt value="DK">Denmark</opt>
        <opt value="DJ">Djibouti</opt>
        <opt value="DM">Dominica</opt>
        <opt value="DO">Dominican Republic</opt>
        <opt value="TP">East Timor</opt>
        <opt value="EC">Ecuador</opt>
        <opt value="EG">Egypt</opt>
        <opt value="SV">El Salvador</opt>
        <opt value="GQ">Equatorial Guinea</opt>
        <opt value="ER">Eritrea</opt>
        <opt value="EE">Estonia</opt>
        <opt value="ET">Ethiopia</opt>
        <opt value="FK">Falkland Islands (Malvinas)</opt>
        <opt value="FO">Faroe Islands</opt>
        <opt value="FJ">Fiji</opt>
        <opt value="FI">Finland</opt>
        <opt value="FR">France</opt>
        <opt value="FX">Metropolitan France</opt>
        <opt value="GF">French Guiana</opt>
        <opt value="PF">French Polynesia</opt>
        <opt value="TF">French Southern Territories</opt>
        <opt value="GA">Gabon</opt>
        <opt value="GM">Gambia</opt>
        <opt value="GE">Georgia</opt>
        <opt value="DE">Germany</opt>
        <opt value="GH">Ghana</opt>
        <opt value="GI">Gibraltar</opt>
        <opt value="GB">Great Britain</opt>
        <opt value="GR">Greece</opt>
        <opt value="GL">Greenland</opt>
        <opt value="GD">Grenada</opt>
        <opt value="GP">Guadeloupe</opt>
        <opt value="GU">Guam</opt>
        <opt value="GT">Guatemala</opt>
        <opt value="GN">Guinea</opt>
        <opt value="GW">Guinea-Bissau</opt>
        <opt value="GY">Guyana</opt>
        <opt value="HT">Haiti</opt>
        <opt value="HM">Heard and Mc Donald Islands</opt>
        <opt value="VA">Holy See (Vatican City State)</opt>
        <opt value="HN">Honduras</opt>
        <opt value="HK">Hong Kong</opt>
        <opt value="HU">Hungary</opt>
        <opt value="IS">Iceland</opt>
        <opt value="IN">India</opt>
        <opt value="ID">Indonesia</opt>
        <opt value="IR">Iran (Islamic Republic of)</opt>
        <opt value="IQ">Iraq</opt>
        <opt value="IE">Ireland</opt>
        <opt value="IL">Israel</opt>
        <opt value="IT">Italy</opt>
        <opt value="JM">Jamaica</opt>
        <opt value="JP">Japan</opt>
        <opt value="JO">Jordan</opt>
        <opt value="KZ">Kazakhstan</opt>
        <opt value="KE">Kenya</opt>
        <opt value="KI">Kiribati</opt>
        <opt value="KP">Democratic People&#39;s Republic of Korea</opt>
        <opt value="KR">Republic of Korea</opt>
        <opt value="KW">Kuwait</opt>
        <opt value="KG">Kyrgyzstan</opt>
        <opt value="LA">Lao People&#39;s Democratic Republic</opt>
        <opt value="LV">Latvia</opt>
        <opt value="LB">Lebanon</opt>
        <opt value="LS">Lesotho</opt>
        <opt value="LR">Liberia</opt>
        <opt value="LY">Libyan Arab Jamahiriya</opt>
        <opt value="LI">Liechtenstein</opt>
        <opt value="LT">Lithuania</opt>
        <opt value="LU">Luxembourg</opt>
        <opt value="MO">Macau</opt>
        <opt value="MK">Republic of Macedonia</opt>
        <opt value="MG">Madagascar</opt>
        <opt value="MW">Malawi</opt>
        <opt value="MY">Malaysia</opt>
        <opt value="MV">Maldives</opt>
        <opt value="ML">Mali</opt>
        <opt value="MT">Malta</opt>
        <opt value="MH">Marshall Islands</opt>
        <opt value="MQ">Martinique</opt>
        <opt value="MR">Mauritania</opt>
        <opt value="MU">Mauritius</opt>
        <opt value="YT">Mayotte</opt>
        <opt value="MX">Mexico</opt>
        <opt value="FM">Federated States of Micronesia</opt>
        <opt value="MD">Republic of Moldova</opt>
        <opt value="MC">Monaco</opt>
        <opt value="MN">Mongolia</opt>
        <opt value="MS">Montserrat</opt>
        <opt value="MA">Morocco</opt>
        <opt value="MZ">Mozambique</opt>
        <opt value="MM">Myanmar</opt>
        <opt value="NA">Namibia</opt>
        <opt value="NR">Nauru</opt>
        <opt value="NP">Nepal</opt>
        <opt value="NL">Netherlands</opt>
        <opt value="AN">Netherlands Antilles</opt>
        <opt value="NC">New Caledonia</opt>
        <opt value="NZ">New Zealand</opt>
        <opt value="NI">Nicaragua</opt>
        <opt value="NE">Niger</opt>
        <opt value="NG">Nigeria</opt>
        <opt value="NU">Niue</opt>
        <opt value="NF">Norfolk Island</opt>
        <opt value="MP">Northern Mariana Islands</opt>
        <opt value="NO">Norway</opt>
        <opt value="OM">Oman</opt>
        <opt value="PK">Pakistan</opt>
        <opt value="PW">Palau</opt>
        <opt value="PA">Panama</opt>
        <opt value="PG">Papua New Guinea</opt>
        <opt value="PY">Paraguay</opt>
        <opt value="PE">Peru</opt>
        <opt value="PH">Philippines</opt>
        <opt value="PN">Pitcairn</opt>
        <opt value="PL">Poland</opt>
        <opt value="PT">Portugal</opt>
        <opt value="PR">Puerto Rico</opt>
        <opt value="QA">Qatar</opt>
        <opt value="RE">Reunion</opt>
        <opt value="RO">Romania</opt>
        <opt value="RU">Russian Federation</opt>
        <opt value="RW">Rwanda</opt>
        <opt value="KN">Saint Kitts and Nevis</opt>
        <opt value="LC">Saint Lucia</opt>
        <opt value="VC">Saint Vincent and the Grenadines</opt>
        <opt value="WS">Samoa</opt>
        <opt value="SM">San Marino</opt>
        <opt value="ST">Sao Tome and Principe</opt>
        <opt value="SA">Saudi Arabia</opt>
        <opt value="SN">Senegal</opt>
        <opt value="SC">Seychelles</opt>
        <opt value="SL">Sierra Leone</opt>
        <opt value="SG">Singapore</opt>
        <opt value="SK">Slovakia (Slovak Republic)</opt>
        <opt value="SI">Slovenia</opt>
        <opt value="SB">Solomon Islands</opt>
        <opt value="SO">Somalia</opt>
        <opt value="ZA">South Africa</opt>
        <opt value="GS">South Georgia and the South Sandwich Islands</opt>
        <opt value="ES">Spain</opt>
        <opt value="LK">Sri Lanka</opt>
        <opt value="SH">St. Helena</opt>
        <opt value="PM">St. Pierre and Miquelon</opt>
        <opt value="SD">Sudan</opt>
        <opt value="SR">Suriname</opt>
        <opt value="SJ">Svalbard and Jan Mayen Islands</opt>
        <opt value="SZ">Swaziland</opt>
        <opt value="SE">Sweden</opt>
        <opt value="CH">Switzerland</opt>
        <opt value="SY">Syrian Arab Republic</opt>
        <opt value="TW">Taiwan</opt>
        <opt value="TJ">Tajikistan</opt>
        <opt value="TZ">United Republic of Tanzania</opt>
        <opt value="TH">Thailand</opt>
        <opt value="TG">Togo</opt>
        <opt value="TK">Tokelau</opt>
        <opt value="TO">Tonga</opt>
        <opt value="TT">Trinidad and Tobago</opt>
        <opt value="TN">Tunisia</opt>
        <opt value="TR">Turkey</opt>
        <opt value="TM">Turkmenistan</opt>
        <opt value="TC">Turks and Caicos Islands</opt>
        <opt value="TV">Tuvalu</opt>
        <opt value="UG">Uganda</opt>
        <opt value="UA">Ukraine</opt>
        <opt value="AE">United Arab Emirates</opt>
        <opt value="UK">United Kingdom</opt>
        <opt value="US">United States</opt>
        <opt value="UM">United States Minor Outlying Islands</opt>
        <opt value="UY">Uruguay</opt>
        <opt value="UZ">Uzbekistan</opt>
        <opt value="VU">Vanuatu</opt>
        <opt value="VE">Venezuela</opt>
        <opt value="VN">Vietnam</opt>
        <opt value="VG">Virgin Islands (British)</opt>
        <opt value="VI">Virgin Islands (U.S.)</opt>
        <opt value="WF">Wallis and Futuna Islands</opt>
        <opt value="EH">Western Sahara</opt>
        <opt value="YE">Yemen</opt>
        <opt value="YU">Yugoslavia</opt>
        <opt value="ZM">Zambia</opt>
        <opt value="ZW">Zimbabwe</opt>
    </set>
</options>